### YAML file for the PPP configuration


device_ID: '3ae678bd-b829-4dbb-acc4-2d041c3afda1' # purple
# device_ID: '58bab427-cbcd-4954-ab76-b49d68d8893d' # silver
#device_ID = '46dcca18-f2e3-4eaf-b366-fad4997ca869' #ONLY FOR BLUE


