bool frontPowerOn			# Turn on/off 
bool frontCostmapEnable     # Enable/disable in costmap
bool rearPowerOn			# Turn on/off 
bool rearCostmapEnable      # Enable/disable in costmap
---
int8 responseCode		# True - success, False - failure
string responseString   # Additional info
