bool front_power_on        # Turn on/off 
bool front_costmap_enable  # Enable/disable in costmap
bool rear_power_on         # Turn on/off 
bool rear_costmap_enable   # Enable/disable in costmap
---
int8 response_code         # 0 = fail, 1 = success
string response_string     # Additional info

