time stamp          # Timestamp
float32 t_offset    # Time offset between GPS and system time
float32 hAcc        # Horizontal accuracy
uint8 gpsQualVal    # Quality value
uint8 numSats       # Number of satellites
float32 horDil      # HDOP
float32 geoSep      # Geoid separation
uint8[] satInfo     # Full satellite information
float32 vCOG        # Velocity - Course over ground (heading) [degrees]
float32 vSOG        # Velocity - Speed over ground (km/h)
